# config.yaml

yolo_weights_path: 'weights/best.pt'
device: 'auto'  # Options: 'auto', 'cuda', 'cpu'
img_size: 640
confidence_threshold: 0.25
iou_threshold: 0.45
classes: null  # List of class indices to filter, e.g., [0, 1, 2]
agnostic_nms: false
api_url: 'http://localhost:8000/predict'        # API endpoint URL
visualize: true                          # Set to true to enable visualization
# Path to the test image
test_image_paths:
  - 'examples/test_image.jpeg'
  - 'examples/test_image2.jpeg'
  - 'examples/test_image3.jpeg'
